### ISSUE TITLE
德文字典網站的連結

### ISSUE THREAD

**Issue by Lanzlanz** [johnyluyte/fetch-online-dictionaries-audio#10]
Hello, thank you very much to create this program. This is very useful. However, I would like to ask for your help. If you could add these German online dictionaries to the list of your program:
https://www.leo.org/englisch-deutsch/
https://www.dict.cc/
https://en.pons.com/translate
People who are learning German will appreciate you very much.
All the best

**Comment by johnyluyte** [comment]
您好，已加入 https://www.leo.org ，請更新至 0.1.28 版。
