### ISSUE TITLE
Cambridge dictionary網頁改版，發音擷取不到

### ISSUE THREAD

**Issue by Yusei-StarDust** [johnyluyte/fetch-online-dictionaries-audio#22]
劍橋字典網頁介面換新，好像擷取不到發音了

**Comment by kinotabi** [comment]
Hi, 這個我已經發過了在 Issues #21 。

我目前是靠用 Safari 瀏覽器，找到網址 /media/english-chinese-traditional/uk_pron 開頭，複製這段網址，貼入 Anki 還是可行的，詳見附圖。在大大還沒有改版前，雖然有點麻煩但是還是可用。

![Screen Shot 2019-09-11 at 9 51 25 AM](https://user-images.githubusercontent.com/8058920/64662203-21391b00-d47a-11e9-88f0-4a26b61416cf.png)

**Comment by johnyluyte** [comment]
您好，已修正，請更新至 0.1.31 版。
