### ISSUE TITLE
Japanesepod101無法擷取

### ISSUE THREAD

**Issue by alvisinjapan** [johnyluyte/fetch-online-dictionaries-audio#23]
版主您好，首先謝謝您無私分享這個非常好用的程式，幫助許多學外語的人！

不過目前似乎無法擷取到Japanesepod101的高音質音檔，不知道您是否可撥冗解決此問題呢？
在此先謝過！我其實也是他們的訂閱者，很希望把他們的高音質錄音加到我的Anki裡。

**Comment by johnyluyte** [comment]
您好，已修正，請更新至 0.1.31 版。
