### ISSUE TITLE
Bad download path in Collins dictionary...

### ISSUE THREAD

**Issue by pityu73** [johnyluyte/fetch-online-dictionaries-audio#29]
Hi!
The download path is bad for collins dictionary. 
- for example download path of "try on" word: https://www.collinsdictionary.com/sounds/hwd_sounds/58348.mp3 
- the programme use this: https://www.collinsdictionary.comhttps//www.collinsdictionary.com/sounds/hwd_sounds/58348.mp3
change it if possible, please
Many thanks

**Comment by IRETD** [comment]
Hello!

Faced with that issue as well.
Made a quick fix and created a PR ;)

**Comment by pityu73** [comment]
It works perfectly and sorry that I responded late.
Thank you for your help.
