### ISSUE TITLE
JapanesePad101字典無法使用

### ISSUE THREAD

**Issue by blue88889** [johnyluyte/fetch-online-dictionaries-audio#5]
https://github.com/johnyluyte/fetch-online-dictionaries-audio#current-supported-sites
這個網站近期不知音檔無法收聽，應該是網頁本身的問題?

**Comment by johnyluyte** [comment]
您好，我這邊沒有做任何更新，但我剛剛試了 japanesepod101 字典中好幾個單字，都可以正常下載發音。請您現在試試看能正常使用嗎？

**Comment by johnyluyte** [comment]
closed due to inactive
