### ISSUE TITLE
複製發音的連結網址後，以往可以直接貼在Anki，但現在需要下載下來再拉到Anki上

### ISSUE THREAD

**Issue by mars102030** [johnyluyte/fetch-online-dictionaries-audio#7]
https://dictionary.cambridge.org

以下是貼到Anki所跳出的訊息：
打開 <urlopen error [Errno 1] _ssl.c:507: error:14077410:SSL routines:SSL23_GET_SERVER_HELLO:sslv3 alert handshake failure> 時發生錯誤

使用mac的chrome上出的問題
謝謝

**Comment by johnyluyte** [comment]
Hi, 我平常也都使用劍橋字典，最近下載發音時的確會出現這個問題。

但由於其他人使用劍橋字典的服務也有遇到此問題： https://ankiweb.net/shared/info/301952613

加上其他網路字典還可以正常使用，合理推測是劍橋字典改變了什麼東西，因此我暫時不會修，抱歉。

**Comment by Josh-YH-Wu** [comment]
Hello ~ 我昨天後來也有用Dictionary.com 發現也不行耶~~
也跳出上述的視窗
那我的系統是win10

**Comment by johnyluyte** [comment]
@Josh-YH-Wu 我剛剛用 Dictionary.com 沒有問題，可以給有問題的連結嗎？

**Comment by Josh-YH-Wu** [comment]
@johnyluyte  不知道為甚麼後來使用又可以了 :)

**Comment by johnyluyte** [comment]
@mars102030 剛剛使用劍橋字典時沒問題了，妳試試看。
