### ISSUE TITLE
請問是否有  截錄youtube影片的一小段聲音檔  的程式呢？：）

### ISSUE THREAD

**Issue by mars102030** [johnyluyte/fetch-online-dictionaries-audio#9]
因為偶而會看voicetube，但是很想擷取其中一小段來幫助在Ａnki複習時回想起當時的情況。

聲音檔好像都是
[sound:           .mp3]開頭的

我想請教一下，是否可以在 原始程式碼抓下幾分幾秒就可以截到這段時間的聲音呢？
ex:[sound: youtube/xxx/2:30 .mp3]

謝謝你:)

**Comment by mars102030** [comment]
已經解決了：）

**Comment by johnyluyte** [comment]
Nice
